-- Run in the Supabase SQL editor (in order):
--   migrations/001_initial_schema.sql
--   migrations/002_storage_plans_by_project.sql
--
-- 001: tables, RLS, private `plans` bucket
-- 002: storage paths {projectId}/{sheetId}/... owned via projects.user_id
